name: config

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-type-defaults
  - -fno-warn-name-shadowing
  - -Wno-type-defaults
  - -fno-warn-missing-pattern-synonym-signatures
  - -j
  - -static
  - -fwrite-ide-info
  - -Wno-name-shadowing


default-extensions:
  - DisambiguateRecordFields
  - NamedFieldPuns

dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - text
  - containers
  - unix

library:
  source-dirs: src

executables:
  config:
    source-dirs: app
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
      - -fwarn-incomplete-patterns
      - -fno-warn-name-shadowing
    dependencies:
    - config